# Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Full Network Deploy"
description: "Creating a Full Network with terraform"
schemaVersion: 1.2.0
version: "20250515"
locale: "es"

#################
# Variables
#################
variableGroups:
  - title: General Configuration
    visible: true
    variables:
      - region
      - compartment_ocid
      - tenancy_ocid
      - network_cidr
      - network_name
      - network_dns

variables:
  region:
    title: Region
    description: The OCI region where the resources will be created.
    type: oci:identity:region:name
    required: true

  compartment_ocid:
    title: Target Compartment
    description: The ID of the Target Compartment where to create all the resources.
    type: oci:identity:compartment:id
    required: true

  tenancy_ocid:
    title: Tennant
    description: The ID of the OCI Tennat.
    type: oci:identity:tennant:id
    required: true

  network_cidr:
    type: string
    title: "CIDR Block for VCN"
    description: "CIDR Block for VCN eg. [10.0 - 10.255, 172.16 - 172.31, 192.168]"
    required: true
    default: "10.0"
    visible: true
    pattern: "^((10.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|(192.168)|(172.(1[6-9]|2[0-9]|3[01])))$"

  network_name:
    title: Network Name
    description: Name of the network without spaces.
    type: string
    default: "MyNetwork"
    required: true
    pattern: ^(([A-Z]{1})([A-Za-z0-9]{1,31}))$

  network_dns:
    title: Network DNS
    description: DNS of the network without spaces.
    type: string
    default: "prod"
    required: true
    pattern: ^(([a-z]{1})([a-z0-9]{1,15}))$